version: '3.12'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  flask:
    build:
      context: .
      dockerfile: Dockerfile
      target: flask_builder
    image: 192.168.29.103/mastek/genaiserver:v1
    container_name: GenAIServer
    ports:
      - "4040:4040"
    command: python app.py
    depends_on:
      - mongo

  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: node_builder
    image: 192.168.29.103/mastek/widget:v1
    container_name: widget
    ports:
      - "3000:3000"
    command: node server.js

volumes:
  mongo_data:
